---
- name: Retrieve Device Information via NETCONF
  hosts: localhost # Ansible will run locally on your management server
  gather_facts: no

  tasks:
    - name: Execute NETCONF Operation
      ncclient_operations:
        host: 192.168.1.1
        port: 830
        username: your_username
        password: your_password
        operation: get # Replace with the NETCONF operation you want to perform
      register: nc_result

    - name: Print NETCONF Result
      debug:
        var: nc_result
